### PR TITLE
+ option: speech without  syncing time

### PR DESCRIPTION
**Pull request by billythekidz**
This is the option using to listening caption only without look into video.

### CODE REVIEW

**Comment by limura** [comment]
Thank you very much.
So you add the option to read everything regardless of the video playback status.

I have checked the PATCH. I have not confirmed that it works yet, but it looks like there are no problems with the program code. Excellent work. Thank you very much.

We are currently in the middle of a larger fix on the other project side, so we are going to have to put off for a bit the response to this project.
So, please let me work on getting this pull request in after we confirm that it works.

Also, if possible, it would be great if you could provide messages.js for other languages as well as English. Machine translated versions would be fine.
If it is too much work, we will do the work ourselves.

**Comment by billythekidz** [comment]
Ok man! I just commit localize in messages.js

**Comment by limura** [comment]
Quick work!
Thanks for adding the localization file.

I will check the operation later.

**Comment by limura** [comment]
Sorry for the delay.

We have checked the operation. I will merge it with the one that seems to have no problem in general.

Thank you very much for your good work. Thank you very much.

**Pull request merged**
